server:
  port: 8085
  max-http-header-size: 102400
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/child_ill_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456

# 日志
logging:
  level:
    com.java.kids.dao: debug

mybatis:
  type-aliases-package: tk.mybatis.springboot.model
  mapper-locations: classpath:mappers/*.xml
  #  设置驼峰命名法
  configuration:
    map-underscore-to-camel-case: true

